(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
	(begin (set! balance
		     (- balance amount))
	       balance)
	"Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch pw m)
    (if (eq? password pw)
	(cond ((eq? m 'withdraw) withdraw)
	      ((eq? m 'deposit) deposit)
	      (else (error "Unknown request: MAKE-ACCOUNT" m)))
	(lambda (ignored) "Incorrect password")))
  dispatch)

(define acc (make-account 100 'mypw))

((acc 'badpw 'withdraw) 50)
((acc 'mypw 'withdraw) 60)
((acc 'badpw 'deposit) 40)
((acc 'mypw 'deposit) 60)
